copy /b "library.zip.0" "library.zip"
copy /b "library.zip"+"library.zip.1"
copy /b "library.zip"+"library.zip.2"
copy /b "library.zip"+"library.zip.3"
copy /b "library.zip"+"library.zip.4"
copy /b "library.zip"+"library.zip.5"
copy /b "library.zip"+"library.zip.6"
copy /b "library.zip"+"library.zip.7"
copy /b "library.zip"+"library.zip.8"
copy /b "library.zip"+"library.zip.9"
copy /b "library.zip"+"library.zip.10"
copy /b "library.zip"+"library.zip.11"
